[package]
name = "regal"
version = "0.2.0"
authors = ["Stephan Göppentin <dedda102@gmail.com>"]
edition = "2018"
description = "regal image gallery for web"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
