-- Your SQL goes here
CREATE TABLE images (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR(200) NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    gallery_id INTEGER NOT NULL,
    format VARCHAR(10) NOT NULL,
    path VARCHAR(255) NOT NULL UNIQUE,
    sha1 VARCHAR(40) NOT NULL,
    filesize INTEGER NOT NULL,
    external_id VARCHAR(40) UNIQUE NOT NULL
)