-- Your SQL goes here
CREATE TABLE tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    tag_type INTEGER NOT NULL DEFAULT 1,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE image_tags (
    tag_id INTEGER NOT NULL,
    image_id INTEGER NOT NULL,
    CONSTRAINT image_tag_pk PRIMARY KEY(tag_id, image_id),
    FOREIGN KEY(tag_id) REFERENCES tag(id) ON DELETE CASCADE,
    FOREIGN KEY(image_id) REFERENCES image(id) ON DELETE CASCADE
)